%YAML:1.0

Version: 1.0

#--------------------------------------------------------------------------------------------
# General Parameters
#--------------------------------------------------------------------------------------------


#--------------------------------------------------------------------------------------------
# General Parameters (fixed).
#--------------------------------------------------------------------------------------------
# original image size for camera
width: 240
height: 180

#--------------------------------------------------------------------------------------------
# Input Parameters
#--------------------------------------------------------------------------------------------
# groundtruth_dir: "/home/hxy/Documents/rosbag/Mono-unzip/poster_rotation/events.txt"
# groundtruth_dir: "/home/hxy/Documents/rosbag/Mono-unzip/shapes_rotation/events.txt"
# groundtruth_dir: "/home/hxy/Documents/rosbag/Mono-unzip/boxes_rotation/events.txt"
groundtruth_dir: "/home/hxy/Documents/rosbag/Mono-unzip/dynamic_rotation/events.txt"
output_dir: "/home/hxy/Desktop/hxy-rotation/data/ransac_.txt"


# 2.7e7~3.1e7 for dynamic 
# 5.7e6~5.9e6 for shapes 
# you can use 
read_start_lines: 999e4
read_max_lines: 10e7

#--------------------------------------------------------------------------------------------
# Event Parameters
#--------------------------------------------------------------------------------------------
Event.delta_time: 0.01
using_fixed_time: 0  # 1 means true

fixed_interval: 0.003
Event.bundle_size: 3e4 