%YAML:1.0

Version: 1.0

#--------------------------------------------------------------------------------------------
# General Parameters
#--------------------------------------------------------------------------------------------


#--------------------------------------------------------------------------------------------
# General Parameters (fixed).
#--------------------------------------------------------------------------------------------
# original image size for camera
width: 240
height: 180

#--------------------------------------------------------------------------------------------
# Input Parameters
#--------------------------------------------------------------------------------------------
groundtruth_dir: "/home/hxy/Documents/rosbag/Mono-unzip/poster_rotation/events.txt"
# output_dir: "/home/hxy/Desktop/hxy-rotation/data/ransac_size10k_double_warp_10000_timerange(0.4)_iter15.txt"
output_dir: "/home/hxy/Desktop/hxy-rotation/data/ransac_size30k_double_warp_8000_timerange(0.4)_iter30_ceres20_gaussian1.txt"
# output_dir: "/home/hxy/Desktop/hxy-rotation/data/sample_test.txt"


# 2.7e7~3.1e7 for dynamic 
# 5.7e6~5.9e6 for shapes 
# you can use 
read_start_lines: 0e4
read_max_lines: 25000e4
# read_start_lines: 5000e4
# read_max_lines: 5003e4
#--------------------------------------------------------------------------------------------
# Event Parameters
#--------------------------------------------------------------------------------------------
Event.delta_time: 0.01
using_fixed_time: 0  # 1 means true

fixed_interval: 0.02
Event.bundle_size: 3e4 