%YAML:1.0

Version: 1.0

#--------------------------------------------------------------------------------------------
# General Parameters
#--------------------------------------------------------------------------------------------


#--------------------------------------------------------------------------------------------
# General Parameters (fixed).
#--------------------------------------------------------------------------------------------
# original image size for camera
# width: 240
# height: 180

#--------------------------------------------------------------------------------------------
# Input Parameters
#--------------------------------------------------------------------------------------------
# groundtruth_dir: "/home/hxy/Documents/rosbag/Mono-unzip/poster_rotation/events.txt"
# groundtruth_dir: "/home/hxy/Documents/rosbag/Mono-unzip/dynamic_rotation/events.txt"
# groundtruth_dir: "/home/hxy/Documents/rosbag/Mono-unzip/boxes_rotation/events.txt"
groundtruth_dir: "/home/hxy/Documents/rosbag/Mono-unzip/shapes_rotation/events.txt"
# output_dir: "/home/hxy/Desktop/ECCV22-all/hxy-rotation/data/rotation_estimation/poster_rotation/221106_RT2_deltat_0.015_single_warp_"
# output_dir: "/home/hxy/Desktop/ECCV22-all/hxy-rotation/data/rotation_estimation/dynamic_rotation/221106_RT_deltat_0.015_single_warp_"
# output_dir: "/home/hxy/Desktop/ECCV22-all/hxy-rotation/data/rotation_estimation/boxes_rotation/221106_baset0.01_final5_resetzero_dynasize5k_double_warp_"
output_dir: "/home/hxy/Desktop/ECCV22-all/hxy-rotation/data/rotation_estimation/shapes_rotation/221108_baset0.01_final5_resetzero_dynasize5k_double_warp_"

# DVS_MOTION
# groundtruth_dir: "/home/hxy/Documents/rosbag/DVSMOTION20/Camera_Motion_Data_Mat/checkerboard_sequence/events.txt"
# output_dir: "/home/hxy/Desktop/ECCV22-all/hxy-rotation/data/rotation_estimation/checkerboard_sequence/221106_baset0.01_final5_resetzero_dynasize5k_double_warp_"
# groundtruth_dir: "/home/hxy/Documents/rosbag/DVSMOTION20/Camera_Motion_Data_Mat/classroom_sequence/events.txt"
# output_dir: "/home/hxy/Desktop/ECCV22-all/hxy-rotation/data/rotation_estimation/classroom_sequence/221106_RT_deltat_0.015_single_warp_"
# groundtruth_dir: "/home/hxy/Documents/rosbag/DVSMOTION20/Camera_Motion_Data_Mat/conference_sequence/events.txt"
# output_dir: "/home/hxy/Desktop/ECCV22-all/hxy-rotation/data/rotation_estimation/conference_sequence/221106_baset0.01_final5_resetzero_dynasize5k_double_warp_"
 
# 注意改数据集代码需要更改 内参
# 改double double需要更改 GetInsideRatiodouble版本
yaml_sample_count: 1000
yaml_iter_num: 2
yaml_iter_num_final: 5
yaml_ceres_iter_num: 10
yaml_ceres_iter_thread: 16
yaml_ts_start: 0.8
yaml_ts_end: 0.8
yaml_denoise_num: 4
yaml_gaussian_size: 5
yaml_gaussian_size_sigma: 1
yaml_default_value_factor: 1
yaml_ros_starttime: 0
# yaml_ros_starttime: 1468940145.2311351 # ros poster 1468940145.2311351, boxes 1468940843.8233166, dynamic 1473347265.9092634, shapes 1468939802.870256
# 2.7e7~3.1e7 for dynamic 
# 5.7e6~5.9e6 for shapes 
# you can use 
read_start_lines: 0e4
read_max_lines: 25000e4
# read_start_lines: 1300e4
# read_max_lines: 1600e4

#--------------------------------------------------------------------------------------------
# Event Parameters
#--------------------------------------------------------------------------------------------
Event.delta_time: 0.01
using_fixed_time: 0  # 1 means true

fixed_interval: 0.02
Event.bundle_size: 5e3 

# for dynamic batch 
yaml_outlier_ratio: 50
yaml_time_length: 33
yaml_batch_length: 150