%YAML:1.0

Version: 1.0

#--------------------------------------------------------------------------------------------
# General Parameters
#--------------------------------------------------------------------------------------------


#--------------------------------------------------------------------------------------------
# General Parameters (fixed).
#--------------------------------------------------------------------------------------------
# original image size for camera
# width: 240
# height: 180

#--------------------------------------------------------------------------------------------
# Input Parameters
#--------------------------------------------------------------------------------------------
# groundtruth_dir: "/home/hxy/Documents/rosbag/Mono-unzip/slider_far/events.txt"
groundtruth_dir: "/home/hxy/Documents/rosbag/Mono-unzip/slider_close/events.txt"
# groundtruth_dir: "/home/hxy/Documents/rosbag/Zhu-RAL/cycle.txt"
# groundtruth_dir: "/home/hxy/Documents/rosbag/Mono-unzip/dynamic_rotation/events.txt"
# groundtruth_dir: "/home/hxy/Documents/rosbag/Mono-unzip/boxes_rotation/events.txt"
# output_dir: "/home/hxy/Desktop/hxy-rotation/data/rotation_estimation/poster_rotation/RT_second_order_size30k_dsingle_warp_"
# output_dir: "/home/hxy/Desktop/hxy-rotation/data/rotation_estimation/dynamic_rotation/RT_second_order_size30k_single_warp_"
output_dir: "/home/hxy/Desktop/hxy-rotation/data/translation_estimation/slider_far/size10k_single_warp_"

yaml_sample_count: 5000
yaml_iter_num: 10
yaml_ceres_iter_num: 2
yaml_ceres_iter_thread: 16
yaml_ts_start: 0.8
yaml_ts_end: 0.8
yaml_denoise_num: 4
yaml_gaussian_size: 3
yaml_gaussian_size_sigma: 1
yaml_default_value_factor: 1.5
yaml_ros_starttime: 0 # poster 1468940145.2311351, boxes 1468940843.8233166, dynamic 1473347265.9092634
# 2.7e7~3.1e7 for dynamic 
# 5.7e6~5.9e6 for shapes 
# you can use 
# read_start_lines: 0e4
# read_max_lines: 25000e4
read_start_lines: 7e4
read_max_lines: 9e4


#--------------------------------------------------------------------------------------------
# Event Parameters
#--------------------------------------------------------------------------------------------
Event.delta_time: 0.01
using_fixed_time: 0  # 1 means true

fixed_interval: 0.02
Event.bundle_size: 2e4 