%YAML:1.0

Version: 1.0

#--------------------------------------------------------------------------------------------
# General Parameters
#--------------------------------------------------------------------------------------------


#--------------------------------------------------------------------------------------------
# General Parameters (fixed).
#--------------------------------------------------------------------------------------------
# original image size for camera
# width: 240
# height: 180

#--------------------------------------------------------------------------------------------
# Input Parameters
#--------------------------------------------------------------------------------------------
# groundtruth_dir: "/home/hxy/Documents/rosbag/Mono-unzip/poster_6dof/events.txt"
# groundtruth_dir: "/home/hxy/Documents/rosbag/Mono-unzip/poster_translation/events.txt"
# groundtruth_dir: "/home/hxy/Documents/rosbag/Mono-unzip/poster_hdr/events.txt"
groundtruth_dir: "/home/hxy/Documents/rosbag/Mono-unzip/simulation_3walls/events.txt"

# output_dir: "/home/hxy/Desktop/hxy-rotation/data/planar_estimation/poster_6dof/temp_single_inv_exactly_norm3d_size30k_"
# output_dir: "/home/hxy/Desktop/hxy-rotation/data/planar_estimation/poster_translation/temp_new1_single_inv_exactly_norm3d_size30k_"
# output_dir: "/home/hxy/Desktop/hxy-rotation/data/planar_estimation/poster_hdr/temp_single_inv_exactly_norm3d_size30k_"
output_dir: "/home/hxy/Desktop/hxy-rotation/data/planar_estimation/simulation_3walls/single_inv_exactly_norm3d_size10k_"

yaml_sample_count: 3000
yaml_iter_num: 10
yaml_ceres_iter_num: 10
yaml_ceres_iter_thread: 4
yaml_ts_start: 0.8
yaml_ts_end: 0.8
yaml_denoise_num: 4
yaml_gaussian_size: 5
yaml_gaussian_size_sigma: 1
yaml_default_value_factor: 1
yaml_regulization_factor: 10


# 2.7e7~3.1e7 for dynamic 
# 5.7e6~5.9e6 for shapes 
# you can use 
read_start_lines: 0e4
read_max_lines: 25000e4
# read_start_lines: 100e4
# read_max_lines:  250e4


#--------------------------------------------------------------------------------------------
# Event Parameters
#--------------------------------------------------------------------------------------------
Event.delta_time: 0.01
using_fixed_time: 0  # 1 means true

fixed_interval: 0.02
Event.bundle_size: 1e4 