%YAML:1.0

Version: 1.0

#--------------------------------------------------------------------------------------------
# General Parameters (fixed).
#--------------------------------------------------------------------------------------------
# original image size for camera
width: 346
height: 260

#--------------------------------------------------------------------------------------------
# Event Parameters (tunable).
#--------------------------------------------------------------------------------------------
# size of real targets
Event.delta_time: 0.1
Event.max_event: 5e4
Event.min_event: 20000
Event.start_line: 0e4
Event.end_line: 25000e4
# Event.end_line: 250e4